--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/ItemCooldowns
build-by-default: true
branches:
- PM4
projects:
  ItemCooldowns:
    path: ""
    icon: Logo.png
    lint:
      phpstan: false
...
